// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvsgmhtovshmipbfugso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2c2dtaHRvdnNobWlwYmZ1Z3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MDQwMDgsImV4cCI6MjA2MzQ4MDAwOH0.kGiAPN_XzF87GcLsm_4n2yy7vgBLdi_NyCt1F2IAq7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);